baseURL = "https://dhpopi.github.io/"
languageCode = "zh-cn"
title = "dhpopi"
theme = "PaperMod"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true   # 首页不要“首篇特殊展示”，更克制
  hideSummary = true             # 列表不显示摘要（更像 diygod）

  showtoc = true
  tocopen = false
  mainSections = ["posts"]


  # 首页顶部简介块（极简）
  [params.homeInfoParams]
    Title = "dhpopi"
    Content = "一只留学PY的苦中作乐罢了"

  # 社交链接（可增删）
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dhpopi"

  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/17078573"

  [[params.socialIcons]]
    name = "steam"
    url = "https://steamcommunity.com/profiles/76561198963105829/"

  [[params.socialIcons]]
    name = "outlook"
    url = "francis.guo@mail.utoronto.ca"

  # 顶部菜单（极简导航）
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4
